doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataClassificationBundle: ~
                    ApplicationSonataClassificationBundle: ~
                    SonataMediaBundle: ~
                    ApplicationSonataMediaBundle: ~

    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType