doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataMediaBundle: ~

    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType