services:
    admin.user:
        class: AdminBundle\Admin\UserAdmin
        arguments: [~, UserBundle\Entity\User, ~, '@doctrine.orm.entity_manager']
        tags:
            - { name: sonata.admin, manager_type: orm, group: Utilisateurs, label: Gestion des utilisateurs }

    admin.education:
        class: AdminBundle\Admin\EducationAdmin
        arguments: [~, ResumeBundle\Entity\Education, AdminBundle:EducationAdmin, '@doctrine.orm.entity_manager']
        tags:
            - { name: sonata.admin, manager_type: orm, group: CV, label: Diplômes }

    admin.experience:
        class: AdminBundle\Admin\ExperienceAdmin
        arguments: [~, ResumeBundle\Entity\Experience, AdminBundle:ExperienceAdmin, '@doctrine.orm.entity_manager']
        tags:
            - { name: sonata.admin, manager_type: orm, group: CV, label: Expériences }