services:
    admin.user:
        class: AdminBundle\Admin\UserAdmin
        arguments: [~, UserBundle\Entity\User, AdminBundle:UserAdmin, '@security.token_storage', '@security.authorization_checker', '@doctrine.orm.entity_manager']
        tags:
            - { name: sonata.admin, manager_type: orm, group: Utilisateurs, label: Liste des utilisateurs }

    admin.education:
        class: AdminBundle\Admin\EducationAdmin
        arguments: [~, ResumeBundle\Entity\Education, AdminBundle:EducationAdmin, '@security.token_storage', '@doctrine.orm.entity_manager']
        tags:
            - { name: sonata.admin, manager_type: orm, group: CV, label: Diplômes }

    admin.experience:
        class: AdminBundle\Admin\ExperienceAdmin
        arguments: [~, ResumeBundle\Entity\Experience, AdminBundle:ExperienceAdmin, '@security.token_storage', '@doctrine.orm.entity_manager']
        tags:
            - { name: sonata.admin, manager_type: orm, group: CV, label: Expériences }

    admin.skill:
        class: AdminBundle\Admin\SkillAdmin
        arguments: [~, ResumeBundle\Entity\Skill, AdminBundle:SkillAdmin, '@security.token_storage', '@doctrine.orm.entity_manager']
        tags:
            - { name: sonata.admin, manager_type: orm, group: CV, label: Compétances }

    admin.service:
        class: AdminBundle\Admin\ServiceAdmin
        arguments: [~, ResumeBundle\Entity\Service, AdminBundle:ServiceAdmin, '@security.token_storage', '@doctrine.orm.entity_manager']
        tags:
            - { name: sonata.admin, manager_type: orm, group: CV, label: Services }

    admin.hobby:
        class: AdminBundle\Admin\HobbyAdmin
        arguments: [~, ResumeBundle\Entity\Hobby, AdminBundle:HobbyAdmin, '@security.token_storage', '@doctrine.orm.entity_manager']
        tags:
            - { name: sonata.admin, manager_type: orm, group: CV, label: Intérêts }

    admin.portfolio:
        class: AdminBundle\Admin\PortfolioAdmin
        arguments: [~, ResumeBundle\Entity\Portfolio, AdminBundle:PortfolioAdmin, '@security.token_storage', '@doctrine.orm.entity_manager']
        tags:
            - { name: sonata.admin, manager_type: orm, group: CV, label: Portfolio }

    admin.project:
        class: AdminBundle\Admin\ProjectAdmin
        arguments: [~, ResumeBundle\Entity\Project, AdminBundle:ProjectAdmin, '@security.token_storage', '@doctrine.orm.entity_manager']
        tags:
            - { name: sonata.admin, manager_type: orm, group: CV, label: Projets }