user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

inspinia:
    resource: "@InspiniaBundle/Resources/config/routing.yml"
    prefix:   /

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
