<?php

namespace ResumeBundle\Repository;

use ResumeBundle\Entity\Portfolio;
use ResumeBundle\Entity\Project;
use UserBundle\Entity\User;

/**
 * PortfolioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolioRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Project $project
     * @return null | Portfolio
     */
    public function getProjectPortfolio(Project $project)
    {
        $qb = $this->createQueryBuilder('p');

        $qb
        ->andWhere($qb->expr()->isMemberOf(':project', 'p.projects'))
        ->setParameter('project', $project);
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @param User $user
     * @return null | Portfolio
     */
    public function getMainPortfolio(User $user)
    {
        $qb = $this->createQueryBuilder('p');

        $qb
        ->where('p.mainPortfolio = true')
        ->andWhere('p in (:portfolios)')
        ->setParameter('portfolios', $user->getPortfolios());

        return $qb->getQuery()->getOneOrNullResult();
    }
}
