<?php

namespace ResumeBundle\Repository;

use ResumeBundle\Entity\Project;

/**
 * PortfolioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolioRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPortfolio(Project $project)
    {
        $qb = $this->createQueryBuilder('p');

        $qb
        ->andWhere($qb->expr()->isMemberOf(':project', 'p.projects'))
        ->setParameter('project', $project);
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }
}
