<?php

namespace ResumeBundle\Repository;

/**
 * PreferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreferencesRepository extends \Doctrine\ORM\EntityRepository
{
}
