sonata_media:
    class:
        media: Application\Sonata\MediaBundle\Entity\Media
        gallery: Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: Application\Sonata\MediaBundle\Entity\GalleryHasMedia
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    providers:
        file:
            service: sonata.media.provider.file
            allowed_extensions: ['pdf', 'jpg', 'png', 'jpeg']
            allowed_mime_types: ['application/pdf', 'application/x-pdf', 'image/pjpeg', 'image/jpeg', 'image/png', 'image/x-png']
        image:
            service: sonata.media.provider.image
            resizer: sonata.media.resizer.custom
            allowed_extensions: ['pdf', 'jpg', 'png', 'jpeg']
            allowed_mime_types: ['application/pdf', 'application/x-pdf','image/pjpeg', 'image/jpeg', 'image/png', 'image/x-png']
    default_context: default # you need to set a context
    contexts:
        default: # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                admin_list:   { width: 40, height: 40, quality: 80 }
                small:        { width: 100, height: 100, quality: 80 }
                big:          { width: 500, height: 500, quality: 80 }
        user:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                admin_list:   { width: 40, height: 40, quality: 80 }
                small:        { width: 60, height: 60, quality: 80 }
                medium:       { width: 80, height: 80, quality: 80 }
                big:          { width: 500, height: 500, quality: 80 }
        avatars:
            providers:
                - sonata.media.provider.image

            formats:
                admin_list:   { width: 40, height: 40, quality: 80 }
                small:        { width: 60, height: 60, quality: 80 }
                medium:       { width: 80, height: 80, quality: 80 }
                big:          { width: 100, height: 100, quality: 80 }
                120x120:      { width: 120, height: 120, quality: 80 }
                mstone:       { width: 500, height: 680, quality: 80 }
        logos:
            providers:
                - sonata.media.provider.image

            formats:
                admin_list:   { width: 40, height: 40, quality: 80 }
                small:        { width: 60, height: 60, quality: 80 }
                medium:       { width: 80, height: 80, quality: 80 }
                big:          { width: 500, height: 500, quality: 80 }

        portfolio:
            providers:
                - sonata.media.provider.image

            formats:
                admin_list:   { width: 40, height: 40, quality: 80 }
                small:        { width: 200, height: 200, quality: 80 }
                medium:       { width: 400, height: 400, quality: 80 }
                big:          { width: 600, height: 600, quality: 80 }

        project:
            providers:
                - sonata.media.provider.image

            formats:
                admin_list:       { width: 40, height: 40, quality: 80 }
                small:            { width: 200, height: 200, quality: 80 }
                medium:           { width: 300, height: 300, quality: 80 }
                big:              { width: 500, height: 500, quality: 80 }
                numo_medium:      { width: 320, height: 340, quality: 80 }
                numo_big:         { width: 640, height: 480, quality: 80 }
                mstone_small:     { width: 160, height: 160, quality: 80 }
                mstone_medium:    { width: 500, height: 680, quality: 80 }
                mstone_big:       { width: 1800, height: 718, quality: 80 }
                mstone_portfolio: { width: 900, height: 600, quality: 80 }

        customer:
            providers:
                - sonata.media.provider.image

            formats:
                admin_list:       { width: 40, height: 40, quality: 80 }
                small:            { width: 200, height: 200, quality: 80 }
                medium:           { width: 300, height: 300, quality: 80 }
                big:              { width: 500, height: 500, quality: 80 }
                numo_medium:      { width: 320, height: 340, quality: 80 }
                numo_big:         { width: 640, height: 480, quality: 80 }
                mstone_small:     { width: 160, height: 160, quality: 80 }
                mstone_medium:    { width: 500, height: 680, quality: 80 }
                mstone_big:       { width: 1800, height: 718, quality: 80 }
                mstone_customer:  { width: 160, height: 160, quality: 80 }

        blog:
            providers:
                - sonata.media.provider.image

            formats:
                admin_list:       { width: 40, height: 40, quality: 80 }
                small:            { width: 200, height: 200, quality: 80 }
                medium:           { width: 300, height: 300, quality: 80 }
                big:              { width: 500, height: 500, quality: 80 }
                numo_medium:      { width: 650, height: 220, quality: 80 }
                numo_big:         { width: 650, height: 480, quality: 80 }
                mstone_small:     { width: 160, height: 160, quality: 80 }
                mstone_medium:    { width: 650, height: 480, quality: 80 }
                mstone_big:       { width: 1800, height: 718, quality: 80 }
                mstone_customer:  { width: 160, height: 160, quality: 80 }
    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false

    providers:
        image:
            resizer: sonata.media.resizer.square