sonata_media:
    class:
        media: Application\Sonata\MediaBundle\Entity\Media
        gallery: Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: Application\Sonata\MediaBundle\Entity\GalleryHasMedia
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    providers:
        file:
            service: sonata.media.provider.file
            allowed_extensions: ['pdf', 'jpg', 'png', 'jpeg']
            allowed_mime_types: ['application/pdf', 'application/x-pdf', 'image/pjpeg', 'image/jpeg', 'image/png', 'image/x-png']
        image:
            service: sonata.media.provider.image
            resizer: sonata.media.resizer.custom
            allowed_extensions: ['pdf', 'jpg', 'png', 'jpeg']
            allowed_mime_types: ['application/pdf', 'application/x-pdf','image/pjpeg', 'image/jpeg', 'image/png', 'image/x-png']
    default_context: default # you need to set a context
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100, height: 100, quality: 100 }
                big:   { width: 500, height: 500, quality: 100 }
        user:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 60, height: 60, quality: 100 }
                medium: { width: 80, height: 80, quality: 100 }
                big:   { width: 500, height: 500, quality: 100 }
        avatar:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 60, height: 60, quality: 100 }
                medium: { width: 80, height: 80, quality: 100 }
                big:   { width: 500, height: 500, quality: 100 }
    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false

    providers:
        image:
            resizer: sonata.media.resizer.square