resume_homepage:
    path:     /{username}
    defaults:
        _controller: ResumeBundle:Index:index
        username: null

resume_unlock:
    path:     /{username}/deverouiller
    defaults:
        _controller: ResumeBundle:Index:unlock

resume_3color_homepage:
    path:     /{username}/3color
    defaults:
        _controller: ResumeBundle:ThreeColor:index

resume_cvilized_homepage:
    path:     /{username}/cvilized
    defaults:
        _controller: ResumeBundle:CVilized:index

resume_numo_homepage:
    path:     /{username}/numo
    defaults:
        _controller: ResumeBundle:Numo:index

resume_mstone_homepage:
    path:     /{username}/mstone
    defaults:
        _controller: ResumeBundle:MStone:index