resume_homepage:
    path:     /resume/{username}
    defaults:
        _controller: ResumeBundle:Index:index
        username: 'morphinof'

3color_homepage:
    path:     /3color/{username}
    defaults:
        _controller: ResumeBundle:ThreeColor:index

cvilized_homepage:
    path:     /cvilized/{username}
    defaults:
        _controller: ResumeBundle:CVilized:index

numo_homepage:
    path:     /numo/{username}
    defaults:
        _controller: ResumeBundle:Numo:index

mstone_homepage:
    path:     /mstone/{username}
    defaults:
        _controller: ResumeBundle:MStone:index