imports:
    - { resource: twig.yml }

services:
    resume_bundle.class.education:
        class: ResumeBundle\Entity\Education
    resume_bundle.class.experience:
        class: ResumeBundle\Entity\Experience
    resume_bundle.class.portfolio:
        class: ResumeBundle\Entity\Portfolio
    resume_bundle.class.project:
        class: ResumeBundle\Entity\Project

    resume_bundle.form.education:
        class: ResumeBundle\Form\EducationType
        tags:
            - { name: form.type, alias: resume_bundle_education_type }

    resume_bundle.form.experience:
        class: ResumeBundle\Form\ExperienceType
        tags:
            - { name: form.type, alias: resume_bundle_experience_type }

    resume_bundle.form.portfolio:
        class: ResumeBundle\Form\PortfolioType
        tags:
            - { name: form.type, alias: resume_bundle_portfolio_type }

    resume_bundle.form.project:
        class: ResumeBundle\Form\ProjectType
        tags:
            - { name: form.type, alias: resume_bundle_project_type }

    resume_bundle.form.check_seed:
        class: ResumeBundle\Form\CheckSeedType
        arguments:
            - '@user_bundle.user'
        tags:
            - { name: form.type, alias: resume_bundle_check_seed_type }