services:
    user_bundle.user:
        class: UserBundle\Entity\User

    user_bundle.form.profile:
        class: UserBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: user_bundle_profile_type }

    user_bundle.form.contact:
        class: UserBundle\Form\ContactType
        tags:
            - { name: form.type, alias: user_bundle_contact_type }

    user_bundle.form.preferences:
        class: UserBundle\Form\PreferencesType
        tags:
            - { name: form.type, alias: user_bundle_preferences_type }