services:
  user.form.profile:
    class: UserBundle\Form\ProfileType
    arguments:
      - '@security.token_storage'
    tags:
      - { name: form.type, alias: user_bundle_profile_type }

  user.form.contact:
    class: UserBundle\Form\ContactType
    tags:
      - { name: form.type, alias: user_bundle_contact_type }