services:
    # Classes
    user_bundle.class.user:
        class: UserBundle\Entity\User

    # Services
    user_bundle.services.owner:
        class: UserBundle\Service\OwnerService
        arguments:
            - '@doctrine.orm.entity_manager'

    # Extensions
    user_bundle.extensions.owner:
        class: UserBundle\Twig\OwnerExtension
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@user_bundle.services.owner'
        tags:
            - { name: twig.extension }

    # Forms
    user_bundle.forms.registration:
        class: UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: user_bundle_registration }

    user_bundle.forms.registration.step1:
        class: UserBundle\Form\Registration\Step1Type
        tags:
            - { name: form.type, alias: user_bundle_registration_step1 }

    user_bundle.forms.profile:
        class: UserBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: user_bundle_profile_type }

    user_bundle.forms.contact:
        class: UserBundle\Form\ContactType
        tags:
            - { name: form.type, alias: user_bundle_contact_type }

    user_bundle.forms.preferences:
        class: UserBundle\Form\PreferencesType
        tags:
            - { name: form.type, alias: user_bundle_preferences_type }