inspinia_homepage:
    path:     /inspinia
    defaults: { _controller: InspiniaBundle:Default:index }

inspinia_md_skin:
    path:     /inspinia/md-skin
    defaults: { _controller: InspiniaBundle:Default:mdSkin }

inspinia_dashboard2:
    path:     /inspinia/dashboard2
    defaults: { _controller: InspiniaBundle:Default:dashboard2 }

inspinia_dashboard3:
    path:     /inspinia/dashboard3
    defaults: { _controller: InspiniaBundle:Default:dashboard3 }

inspinia_dashboard4:
    path:     /inspinia/dashboard4
    defaults: { _controller: InspiniaBundle:Default:dashboard4 }

inspinia_dashboard4_1:
    path:     /inspinia/dashboard4_1
    defaults: { _controller: InspiniaBundle:Default:dashboard4_1 }

inspinia_dashboard5:
    path:     /inspinia/dashboard5
    defaults: { _controller: InspiniaBundle:Default:dashboard5 }

inspinia_layouts:
    path:     /inspinia/layouts
    defaults: { _controller: InspiniaBundle:Default:layouts }

inspinia_graph_flot:
    path:     /inspinia/graph-flot
    defaults: { _controller: InspiniaBundle:Default:graphFlot }

inspinia_graph_morris:
    path:     /inspinia/graph-morris
    defaults: { _controller: InspiniaBundle:Default:graphMorris }

inspinia_graph_rickshaw:
    path:     /inspinia/graph-rickshaw
    defaults: { _controller: InspiniaBundle:Default:graphRickshaw }

inspinia_graph_chartjs:
    path:     /inspinia/graph-chartjs
    defaults: { _controller: InspiniaBundle:Default:graphChartJs }

inspinia_graph_chartist:
    path:     /inspinia/graph-chartist
    defaults: { _controller: InspiniaBundle:Default:graphChartist }

inspinia_graph_c3:
    path:     /inspinia/graph-c3
    defaults: { _controller: InspiniaBundle:Default:graphC3 }

inspinia_graph_peity:
    path:     /inspinia/graph-peity
    defaults: { _controller: InspiniaBundle:Default:graphPeity }

inspinia_graph_sparkline:
    path:     /inspinia/graph-sparkline
    defaults: { _controller: InspiniaBundle:Default:graphSparkline }

inspinia_mailbox:
    path:     /inspinia/mailbox
    defaults: { _controller: InspiniaBundle:Default:mailbox }

inspinia_mail_detail:
    path:     /inspinia/mail-detail
    defaults: { _controller: InspiniaBundle:Default:mailDetail }

inspinia_mail_compose:
    path:     /inspinia/mail-compose
    defaults: { _controller: InspiniaBundle:Default:mailCompose }

inspinia_email_templates:
    path:     /inspinia/email-templates
    defaults: { _controller: InspiniaBundle:Default:emailTemplates }

inspinia_email_action:
    path:     /inspinia/email/action
    defaults: { _controller: InspiniaBundle:Default:emailAction }

inspinia_email_alert:
    path:     /inspinia/email/alert
    defaults: { _controller: InspiniaBundle:Default:emailAlert }

inspinia_email_billing:
    path:     /inspinia/email/billing
    defaults: { _controller: InspiniaBundle:Default:emailBilling }

inspinia_metrics:
    path:     /inspinia/metrics
    defaults: { _controller: InspiniaBundle:Default:metrics }

inspinia_widgets:
    path:     /inspinia/widgets
    defaults: { _controller: InspiniaBundle:Default:widgets }

inspinia_form_basic:
    path:     /inspinia/form/basic
    defaults: { _controller: InspiniaBundle:Default:formBasic }

inspinia_form_advanced:
    path:     /inspinia/form/advanced
    defaults: { _controller: InspiniaBundle:Default:formAdvanced }

inspinia_form_wizard:
    path:     /inspinia/form/wizard
    defaults: { _controller: InspiniaBundle:Default:formWizard }

inspinia_form_file_upload:
    path:     /inspinia/form/file-upload
    defaults: { _controller: InspiniaBundle:Default:formFileUpload }

inspinia_form_editors:
    path:     /inspinia/form/editors
    defaults: { _controller: InspiniaBundle:Default:formEditors }

inspinia_form_markdown:
    path:     /inspinia/form/markdown
    defaults: { _controller: InspiniaBundle:Default:formMarkdown }

inspinia_contacts:
    path:     /inspinia/contacts
    defaults: { _controller: InspiniaBundle:Default:contacts }

inspinia_profile:
    path:     /inspinia/profile
    defaults: { _controller: InspiniaBundle:Default:profile }

inspinia_profile_2:
    path:     /inspinia/profile-2
    defaults: { _controller: InspiniaBundle:Default:profile2 }

inspinia_contacts_2:
    path:     /inspinia/contacts-2
    defaults: { _controller: InspiniaBundle:Default:contacts2 }

inspinia_projects:
    path:     /inspinia/projects
    defaults: { _controller: InspiniaBundle:Default:projects }

inspinia_project_detail:
    path:     /inspinia/project/detail
    defaults: { _controller: InspiniaBundle:Default:projectDetail }

inspinia_teams_board:
    path:     /inspinia/teams/board
    defaults: { _controller: InspiniaBundle:Default:teamsBoard }

inspinia_social_feed:
    path:     /inspinia/social/feed
    defaults: { _controller: InspiniaBundle:Default:socialFeed }

inspinia_clients:
    path:     /inspinia/clients
    defaults: { _controller: InspiniaBundle:Default:clients }

inspinia_full_height:
    path:     /inspinia/full-height
    defaults: { _controller: InspiniaBundle:Default:fullHeight }

inspinia_vote_list:
    path:     /inspinia/vote-list
    defaults: { _controller: InspiniaBundle:Default:voteList }

inspinia_file_manager:
    path:     /inspinia/file-manager
    defaults: { _controller: InspiniaBundle:Default:fileManager }

inspinia_calendar:
    path:     /inspinia/calendar
    defaults: { _controller: InspiniaBundle:Default:calendar }

inspinia_issue_tracker:
    path:     /inspinia/issue-tracker
    defaults: { _controller: InspiniaBundle:Default:issueTracker }

inspinia_blog:
    path:     /inspinia/blog
    defaults: { _controller: InspiniaBundle:Default:blog }

inspinia_article:
    path:     /inspinia/article
    defaults: { _controller: InspiniaBundle:Default:article }

inspinia_faq:
    path:     /inspinia/faq
    defaults: { _controller: InspiniaBundle:Default:faq }

inspinia_timeline:
    path:     /inspinia/timeline
    defaults: { _controller: InspiniaBundle:Default:timeline }

inspinia_pin_board:
    path:     /inspinia/pin-board
    defaults: { _controller: InspiniaBundle:Default:pinBoard }

inspinia_search_results:
    path:     /inspinia/search-results
    defaults: { _controller: InspiniaBundle:Default:searchResults }

inspinia_lock_screen:
    path:     /inspinia/lock-screen
    defaults: { _controller: InspiniaBundle:Default:lockScreen }

inspinia_invoice:
    path:     /inspinia/invoice
    defaults: { _controller: InspiniaBundle:Default:invoice }

inspinia_invoice_print:
    path:     /inspinia/invoice-print
    defaults: { _controller: InspiniaBundle:Default:invoicePrint }

inspinia_login:
    path:     /inspinia/login
    defaults: { _controller: InspiniaBundle:Default:login }

inspinia_login_v2:
    path:     /inspinia/login-v2
    defaults: { _controller: InspiniaBundle:Default:loginV2 }

inspinia_forgot_password:
    path:     /inspinia/forgot-password
    defaults: { _controller: InspiniaBundle:Default:forgotPassword }

inspinia_register:
    path:     /inspinia/register
    defaults: { _controller: InspiniaBundle:Default:register }

inspinia_404:
    path:     /inspinia/404
    defaults: { _controller: InspiniaBundle:Default:error404 }

inspinia_500:
    path:     /inspinia/500
    defaults: { _controller: InspiniaBundle:Default:error500 }

inspinia_empty_page:
    path:     /inspinia/empty-page
    defaults: { _controller: InspiniaBundle:Default:emptyPage }

inspinia_toastr_notifications:
    path:     /inspinia/toastr-notifications
    defaults: { _controller: InspiniaBundle:Default:toastrNotifications }

inspinia_nestable_list:
    path:     /inspinia/nestable-list
    defaults: { _controller: InspiniaBundle:Default:nestableList }

inspinia_agile_board:
    path:     /inspinia/agile-board
    defaults: { _controller: InspiniaBundle:Default:agileBoard }

inspinia_timeline_2:
    path:     /inspinia/timeline-2
    defaults: { _controller: InspiniaBundle:Default:timeline2 }

inspinia_diff:
    path:     /inspinia/diff
    defaults: { _controller: InspiniaBundle:Default:diff }

inspinia_i18support:
    path:     /inspinia/i18support
    defaults: { _controller: InspiniaBundle:Default:i18support }

inspinia_sweet_alert:
    path:     /inspinia/sweet-alert
    defaults: { _controller: InspiniaBundle:Default:sweetAlert }

inspinia_idle_timer:
    path:     /inspinia/idle-timer
    defaults: { _controller: InspiniaBundle:Default:idleTimer }

inspinia_truncate:
    path:     /inspinia/truncate
    defaults: { _controller: InspiniaBundle:Default:truncate }

inspinia_spinners:
    path:     /inspinia/spinners
    defaults: { _controller: InspiniaBundle:Default:spinners }

inspinia_tinycon:
    path:     /inspinia/tinycon
    defaults: { _controller: InspiniaBundle:Default:tinycon }

inspinia_google_maps:
    path:     /inspinia/google-maps
    defaults: { _controller: InspiniaBundle:Default:googleMaps }

inspinia_code_editor:
    path:     /inspinia/code-editor
    defaults: { _controller: InspiniaBundle:Default:codeEditor }

inspinia_modal_window:
    path:     /inspinia/modal-window
    defaults: { _controller: InspiniaBundle:Default:modalWindow }

inspinia_clipboard:
    path:     /inspinia/clipboard
    defaults: { _controller: InspiniaBundle:Default:clipboard }

inspinia_forum_main:
    path:     /inspinia/forum-main
    defaults: { _controller: InspiniaBundle:Default:forumMain }

inspinia_forum_post:
    path:     /inspinia/forum-post
    defaults: { _controller: InspiniaBundle:Default:forumPost }

inspinia_validation:
    path:     /inspinia/validation
    defaults: { _controller: InspiniaBundle:Default:validation }

inspinia_tree_view:
    path:     /inspinia/tree-view
    defaults: { _controller: InspiniaBundle:Default:treeView }

inspinia_loading_buttons:
    path:     /inspinia/loading-buttons
    defaults: { _controller: InspiniaBundle:Default:loadingButtons }

inspinia_chat_view:
    path:     /inspinia/chat-view
    defaults: { _controller: InspiniaBundle:Default:chatView }

inspinia_masonry:
    path:     /inspinia/masonry
    defaults: { _controller: InspiniaBundle:Default:masonry }

inspinia_tour:
    path:     /inspinia/tour
    defaults: { _controller: InspiniaBundle:Default:tour }

inspinia_typography:
    path:     /inspinia/typography
    defaults: { _controller: InspiniaBundle:Default:typography }

inspinia_icons:
    path:     /inspinia/icons
    defaults: { _controller: InspiniaBundle:Default:icons }

inspinia_draggable_panels:
    path:     /inspinia/draggable-panels
    defaults: { _controller: InspiniaBundle:Default:draggablePanels }

inspinia_resizeable_panels:
    path:     /inspinia/resizeable-panels
    defaults: { _controller: InspiniaBundle:Default:resizeablePanels }

inspinia_buttons:
    path:     /inspinia/buttons
    defaults: { _controller: InspiniaBundle:Default:buttons }

inspinia_video:
    path:     /inspinia/video
    defaults: { _controller: InspiniaBundle:Default:video }

inspinia_tabs_panels:
    path:     /inspinia/tabs-panels
    defaults: { _controller: InspiniaBundle:Default:tabsPanels }

inspinia_tabs:
    path:     /inspinia/tabs
    defaults: { _controller: InspiniaBundle:Default:tabs }

inspinia_notifications:
    path:     /inspinia/notifications
    defaults: { _controller: InspiniaBundle:Default:notifications }

inspinia_badges_labels:
    path:     /inspinia/badges-labels
    defaults: { _controller: InspiniaBundle:Default:badgesLabels }

inspinia_grid_options:
    path:     /inspinia/grid-options
    defaults: { _controller: InspiniaBundle:Default:gridOptions }

inspinia_table_basic:
    path:     /inspinia/table-basic
    defaults: { _controller: InspiniaBundle:Default:tableBasic }

inspinia_table_data_tables:
    path:     /inspinia/table-data-tables
    defaults: { _controller: InspiniaBundle:Default:tableDataTables }

inspinia_table_foo_table:
    path:     /inspinia/table-foo-table
    defaults: { _controller: InspiniaBundle:Default:tableFooTable }

inspinia_table_jq_grid:
    path:     /inspinia/table-jq-grid
    defaults: { _controller: InspiniaBundle:Default:tableJqGrid }

inspinia_e_commerce_products_grid:
    path:     /inspinia/table-e-commerce-products-grid
    defaults: { _controller: InspiniaBundle:Default:eCommerceProductsGrid }

inspinia_e_commerce_products_list:
    path:     /inspinia/table-e-commerce-products-list
    defaults: { _controller: InspiniaBundle:Default:eCommerceProductsList }

inspinia_e_commerce_product:
    path:     /inspinia/table-e-commerce-product
    defaults: { _controller: InspiniaBundle:Default:eCommerceProduct }

inspinia_e_commerce_product_detail:
    path:     /inspinia/table-e-commerce-product-detail
    defaults: { _controller: InspiniaBundle:Default:eCommerceProductDetail }

inspinia_e_commerce_cart:
    path:     /inspinia/table-e-commerce-cart
    defaults: { _controller: InspiniaBundle:Default:eCommerceCart }

inspinia_e_commerce_orders:
    path:     /inspinia/table-e-commerce-orders
    defaults: { _controller: InspiniaBundle:Default:eCommerceOrders }

inspinia_e_commerce_payments:
    path:     /inspinia/table-e-commerce-payments
    defaults: { _controller: InspiniaBundle:Default:eCommercePayments }

inspinia_basic_gallery:
    path:     /inspinia/basic-gallery
    defaults: { _controller: InspiniaBundle:Default:basicGallery }

inspinia_slick_carousel:
    path:     /inspinia/slick-carousel
    defaults: { _controller: InspiniaBundle:Default:slickCarousel }

inspinia_carousel:
    path:     /inspinia/carousel
    defaults: { _controller: InspiniaBundle:Default:carousel }

inspinia_css_animation:
    path:     /inspinia/css-animation
    defaults: { _controller: InspiniaBundle:Default:cssAnimation }

inspinia_package:
    path:     /inspinia/package
    defaults: { _controller: InspiniaBundle:Default:package }

inspinia_off_canvas_menu:
    path:     /inspinia/off-canvas-menu
    defaults: { _controller: InspiniaBundle:Default:offCanvasMenu }

inspinia_landing:
    path:     /inspinia/landing
    defaults: { _controller: InspiniaBundle:Landing:index }