inspinia_homepage:
    path:     /inspinia
    defaults: { _controller: InspiniaBundle:Default:index }

inspinia_dashboard2:
    path:     /inspinia/dashboard2
    defaults: { _controller: InspiniaBundle:Default:dashboard2 }

inspinia_dashboard3:
    path:     /inspinia/dashboard3
    defaults: { _controller: InspiniaBundle:Default:dashboard3 }

inspinia_dashboard4:
    path:     /inspinia/dashboard4
    defaults: { _controller: InspiniaBundle:Default:dashboard4 }

inspinia_dashboard4_1:
    path:     /inspinia/dashboard4_1
    defaults: { _controller: InspiniaBundle:Default:dashboard4_1 }

inspinia_dashboard5:
    path:     /inspinia/dashboard5
    defaults: { _controller: InspiniaBundle:Default:dashboard5 }

inspinia_layouts:
    path:     /inspinia/layouts
    defaults: { _controller: InspiniaBundle:Default:layouts }

inspinia_graph_flot:
    path:     /inspinia/graph-flot
    defaults: { _controller: InspiniaBundle:Default:graphFlot }

inspinia_graph_morris:
    path:     /inspinia/graph-morris
    defaults: { _controller: InspiniaBundle:Default:graphMorris }

inspinia_graph_rickshaw:
    path:     /inspinia/graph-rickshaw
    defaults: { _controller: InspiniaBundle:Default:graphRickshaw }

inspinia_graph_chartjs:
    path:     /inspinia/graph-chartjs
    defaults: { _controller: InspiniaBundle:Default:graphChartJs }

inspinia_graph_chartist:
    path:     /inspinia/graph-chartist
    defaults: { _controller: InspiniaBundle:Default:graphChartist }

inspinia_graph_c3:
    path:     /inspinia/graph-c3
    defaults: { _controller: InspiniaBundle:Default:graphC3 }

inspinia_graph_peity:
    path:     /inspinia/graph-peity
    defaults: { _controller: InspiniaBundle:Default:graphPeity }

inspinia_graph_sparkline:
    path:     /inspinia/graph-sparkline
    defaults: { _controller: InspiniaBundle:Default:graphSparkline }

inspinia_mailbox:
    path:     /inspinia/mailbox
    defaults: { _controller: InspiniaBundle:Default:mailbox }

inspinia_mail_detail:
    path:     /inspinia/mail-detail
    defaults: { _controller: InspiniaBundle:Default:mailDetail }

inspinia_mail_compose:
    path:     /inspinia/mail-compose
    defaults: { _controller: InspiniaBundle:Default:mailCompose }

inspinia_email_templates:
    path:     /inspinia/email-templates
    defaults: { _controller: InspiniaBundle:Default:emailTemplates }

inspinia_email_action:
    path:     /inspinia/email/action
    defaults: { _controller: InspiniaBundle:Default:emailAction }

inspinia_email_alert:
    path:     /inspinia/email/alert
    defaults: { _controller: InspiniaBundle:Default:emailAlert }

inspinia_email_billing:
    path:     /inspinia/email/billing
    defaults: { _controller: InspiniaBundle:Default:emailBilling }

inspinia_metrics:
    path:     /inspinia/metrics
    defaults: { _controller: InspiniaBundle:Default:metrics }

inspinia_widgets:
    path:     /inspinia/widgets
    defaults: { _controller: InspiniaBundle:Default:widgets }

inspinia_form_basic:
    path:     /inspinia/form/basic
    defaults: { _controller: InspiniaBundle:Default:formBasic }

inspinia_form_advanced:
    path:     /inspinia/form/advanced
    defaults: { _controller: InspiniaBundle:Default:formAdvanced }

inspinia_form_wizard:
    path:     /inspinia/form/wizard
    defaults: { _controller: InspiniaBundle:Default:formWizard }

inspinia_form_file_upload:
    path:     /inspinia/form/file-upload
    defaults: { _controller: InspiniaBundle:Default:formFileUpload }

inspinia_form_editors:
    path:     /inspinia/form/editors
    defaults: { _controller: InspiniaBundle:Default:formEditors }

inspinia_form_markdown:
    path:     /inspinia/form/markdown
    defaults: { _controller: InspiniaBundle:Default:formMarkdown }

inspinia_contacts:
    path:     /inspinia/contacts
    defaults: { _controller: InspiniaBundle:Default:contacts }

inspinia_profile:
    path:     /inspinia/profile
    defaults: { _controller: InspiniaBundle:Default:profile }

inspinia_profile_2:
    path:     /inspinia/profile-2
    defaults: { _controller: InspiniaBundle:Default:profile2 }

inspinia_contacts_2:
    path:     /inspinia/contacts-2
    defaults: { _controller: InspiniaBundle:Default:contacts2 }

inspinia_projects:
    path:     /inspinia/projects
    defaults: { _controller: InspiniaBundle:Default:projects }

inspinia_project_detail:
    path:     /inspinia/project/detail
    defaults: { _controller: InspiniaBundle:Default:projectDetail }

inspinia_teams_board:
    path:     /inspinia/teams/board
    defaults: { _controller: InspiniaBundle:Default:teamsBoard }

inspinia_social_feed:
    path:     /inspinia/social/feed
    defaults: { _controller: InspiniaBundle:Default:socialFeed }

inspinia_clients:
    path:     /inspinia/clients
    defaults: { _controller: InspiniaBundle:Default:clients }

inspinia_full_height:
    path:     /inspinia/full-height
    defaults: { _controller: InspiniaBundle:Default:fullHeight }

inspinia_vote_list:
    path:     /inspinia/vote-list
    defaults: { _controller: InspiniaBundle:Default:voteList }

inspinia_file_manager:
    path:     /inspinia/file-manager
    defaults: { _controller: InspiniaBundle:Default:fileManager }

inspinia_calendar:
    path:     /inspinia/calendar
    defaults: { _controller: InspiniaBundle:Default:calendar }

inspinia_issue_tracker:
    path:     /inspinia/issue-tracker
    defaults: { _controller: InspiniaBundle:Default:issueTracker }

inspinia_blog:
    path:     /inspinia/blog
    defaults: { _controller: InspiniaBundle:Default:blog }

inspinia_article:
    path:     /inspinia/article
    defaults: { _controller: InspiniaBundle:Default:article }

inspinia_faq:
    path:     /inspinia/faq
    defaults: { _controller: InspiniaBundle:Default:faq }

inspinia_timeline:
    path:     /inspinia/timeline
    defaults: { _controller: InspiniaBundle:Default:timeline }

inspinia_pin_board:
    path:     /inspinia/pin-board
    defaults: { _controller: InspiniaBundle:Default:pinBoard }